---
jupyter: climrr
callout-appearance: simple
editor:
    render-on-save: true
execute:
    freeze: true
---

# Project Overview: `ClimRR`

In this project we will learn to (+ about):

1. Login and access systems and resources at NERSC[^nersc]
    1. Working with a terminal + ([Intro to Unix](https://earth-env-data-science.github.io/lectures/environment/intro_to_unix.html))
    2. Remote login (`ssh`), password + MFA setup
    3. How to clone (download) a Gitub repository and run the (python) code
       inside of it

2. Working with Python
    1. [Python Overview](./00-GettingStarted/0-python.qmd)
    2. Using Jupyter @ NERSC
        - Whats a notebook?
        - How to use Jupyter, execute code, 
        - How notebooks work, advaExecuting code in notebooks

    3. Understanding basic control flow / structure of Python script
        -
        - getting Python setup _in_ Jupyter[^pain]

3. Working with Geospatial (GIS) Data
    1. [Intro to Geospatial Data](./00-GettingStarted/2-intro.qmd)
    2. Identify and understand some common file types and data formats for GIS data
    3. Perform exploratory data analysis
        - (+ common Python libraries for working with GIS data)
    4. Perform simple visualizations in Python to display different data types (e.g. maps, line charts, interactive visualizations, etc)
        - Using figures to illustrate a point or idea
        - Knowing  what types of plots to use to represent different quantities




[^pain]: Getting Python setup **correctly** can be surprisingly difficult
[^nersc]: [NERSC Documentation — Getting Started](https://docs.nersc.gov/getting-started/)

<!-- This  project explores the intersection of climate data and energy justice, -->
<!-- providing an introductory understanding of data science techniques in assessing -->
<!-- disparate outcomes on vulnerable or underserved populations in the United -->
<!-- States. By shedding light on energy disparities, the project aims to contribute -->
<!-- to the ongoing discussions surrounding energy equity and inform policymakers -->
<!-- and stakeholders for more inclusive energy initiatives. Energy justice refers -->
<!-- to the equitable distribution of clean, affordable, and reliable energy -->
<!-- resources among all communities, regardless of their socioeconomic status or -->
<!-- demographic characteristics. -->
<!---->
<!-- The project focuses on analyzing climate data to assess disparate outcomes in -->
<!-- energy access and consumption across different population groups. By leveraging -->
<!-- introductory data science skills, the study aims to uncover patterns, trends, -->
<!-- and potential disparities in energy justice. -->
<!---->
<!-- The project will involve several key steps. Firstly, relevant climate data, -->
<!-- such as temperature, precipitation, and renewable energy sources, will be -->
<!-- collected from reliable sources. This data will be preprocessed and cleaned to -->
<!-- ensure its quality and usability for analysis. -->
<!---->
<!-- Next, the data will be analyzed using introductory data science techniques. -->
<!-- This may include exploratory data analysis, descriptive statistics, and data -->
<!-- visualization to identify patterns and trends within the dataset. The analysis -->
<!-- will focus on examining energy consumption patterns, renewable energy adoption -->
<!-- rates, and energy affordability across different geographical regions and -->
<!-- demographic groups. -->
<!---->
<!-- To assess disparate outcomes, the project will employ various statistical -->
<!-- techniques to compare energy-related indicators among vulnerable populations. -->
<!-- This may involve analyzing energy access in low-income neighborhoods, -->
<!-- evaluating the impact of energy policies on marginalized communities, or -->
<!-- examining the correlation between energy affordability and socioeconomic -->
<!-- factors. -->
<!---->
<!-- The findings of the analysis will be interpreted to gain insights into the -->
<!-- disparities in energy justice and its impact on vulnerable populations. The -->
<!-- project aims to identify areas where energy inequalities exist and provide a -->
<!-- data-driven foundation for advocating for equitable energy policies and -->
<!-- programs. -->
