author: "Sam Foreman"
affiliation: "Argonne National Laboratory"
date: today
# toc: true
number-sections: true
bibliography: references.bib
# filters:
#   - lua/callouts.lua
execute:
  keep-ipynb: true
  freeze: auto
project:
  render:
    - index.qmd
    - qmd/ClimRR.qmd
    - qmd/iris.qmd
    - qmd/chicago.qmd
  type: website
  output-dir: "docs"
  preview:
    port: 4200
website:
  page-navigation: true
  title: "Intro to HPC Bootcamp"
  site-url: "https://saforem2.github.io/climate-analysis"
  favicon: "./assets/favicon.svg"
  # back-to-top-navigation: true
  reader-mode: true
  navbar:
    background: "#222222"
    foregound: "#f8f8f8"
    # - light:
    #   background: "#1A8FFF"
    #   foreground: "#FDFDFD"
    right:
      - icon: github
        href: https://github.com/saforem2/climate-analysis
        aria-label: GitHub

    # left: auto
      # - href: index.qmd
      #   text: Analysis
      # - href: ./qmd/Climrr.qmd
      #   text: ClimRR
      # - href: ./qmd/iris.qmd
      #   text: Iris
  open-graph: true
  repo-url: https://github.com/saforem2/climate-analysis
  repo-actions: [edit, issue]
  google-analytics: G-XVM2Y822Y1
  sidebar:
    style: "floating"
    search: true
    collapse-level: 1
    contents:
      - section: "ClimRR"
        contents:
          - href: index.qmd
            text: Home
          - href: qmd/ClimRR.qmd
            text: Intro to Geospatial Data
          - href: qmd/chicago.qmd
            text: Chicago Analysis
          - href: qmd/iris.qmd
            text: Extras
  page-footer: 
    left: "Copyright 2023, Sam Foreman" 
    right: 
      - icon: github
        href: https://github.com/saforem2/quarto-examples
      - icon: twitter
        href: https://twitter.com/saforem2
format:
  html:
    toc: true
    self-contained: false
    line-numbers: true
    code-link: true
    # embed-resources: false
    # self-contained-math: false
    toc-location: left
    # embed-resources: true
    page-layout: full
    fig-responsive: true
    anchor-sections: true
    # highlight-style:
    #     dark: atom-one
    #     light: arrow-light
    highlight-style: atom-one
    code-overflow: scroll
    code-fold: show
    code-copy: hover
    code-tools:
      source: repo
      toggle: true
      caption: none
    html-math-method: katex
    css:
      - css/default.css
      - css/code.css
      - css/callouts.css
      - css/code-callout.css
      # - css/quarto-syntax-highlighting.css
      # - css/quarto.css
    theme: 
      dark: [css/common.scss, css/custom.scss]
      light: [css/common.scss, css/light.scss]
    smooth-scroll: true
    citations-hover: true
    footnotes-hover: true
    header-includes: |
      <link href="https://pvinis.github.io/iosevka-webfont/3.4.1/iosevka.css" rel="stylesheet" />
