---
jupyter: climrr
title-block-stytle: default
title-block-banner: false
callout-appearance: simple
editor:
    render-on-save: true
execute:
    freeze: true
---

# Climate Risk \& Resilience Portal

## Climate Scenarios

For completeness, we include text below from [@Burdi:2023climrr]

Climate scenarios are the set of conditions used to represent estimates of
future greenhouse gas (GHG) concentrations in the atmosphere. Climate models
then evaluate how these GHG concentrations affect future (projected) climate.

The data in ClimRR include model results from two future climate scenarios,
called Representative Concentration Pathways (RCPs):

1. **RCP4.5**: in this scenario, human GHG emissions peak around 2040, then
   decline
2. **RCP8.5**: in this scenario, human GHG emissions continue to rise
   throughout the 21-st century

Each RCP is modeled over a **mid-century period** (2045—2054) and
**end-of-century-period** (2081 to 2094). A **historical period** (1995—2004)
is also modeled using GHG concentrations during this period.

## Downscaled Climate Models

A global climate model (GCM) is a complex mathematical representation of the
major climate system components (atmosphere, land surface, ocean, and sea ice)
and their interactions.

These models project climatic conditions at frequent intervals over long
periods of time (e.g., every 3 hours for the next 50—100 years), often with the
purpose of evaluating how one or more GHG scenarios will impact future climate.

Most GCMs project patterns at relatively coarse spatial resolutions, using grid
cells ranging from 100km to 200km.

The climate data presented in this portal has been downscaled to a higher
spatial resolution (12km) to fill a growing need for risk analysis and
resilience planning at the local level.

We use _dynamical downscaling_, which applies the outputs of a GCM as inputs to
a separate, high-resolution regional climate model.

Dynamical downscaling accounts for the physical processes and natural features
of a region, as well as the complex interaction between these elements and
global dynamics under a climate scenario.

Argonne's dynamical downscaling uses the Weather Research and Forecasting (WRF)
model, which is a regional weather model for North America developed by the
National Center for Atmospheric Research.

Scientists at Argonne dynamically downscaled three different GCMs, including:

- **CCSM**: The Community Climate System Model (Version 4) is a coupled global
climate model developed by the University Corporation for Atmospheric Research
with funding from the National Science Foundation, the Department of Energy,
and the National Aeronautics and Space Administration. It is comprised of
atmospheric, land surface, and sea ice submodels that run simultaneously
with a central coupler component.

- **GFDL**: The Geophysical Fluid Dynamics Laboratory at the National Oceanic
and Atmospheric Administration developed the Earth System Model Version 2G
(note: the general convention, which we use, is to use the Laboratory's
abbreviation to identify this model). It includes an atmospheric circulation
model and an oceanic circulation model, and takes into account land, sea ice,
and iceberg dynamics.

- **HadGEM**: The United Kingdom’s Met Office developed the Hadley Global
Environment Model 2—Earth System. It is used for both operational weather
forecasting and climate research, and includes coupled atmosphere‐ocean
analysis and an earth system component that includes dynamic vegetation, ocean
biology, and atmospheric chemistry.

## Ensemble Means

**All** data layers in ClimRR represent a climate variable along with its
associated time period and climate scenario (e.g. mid-century RCP4.5). Each
time period comprises one decade's worth of information:

- **historical**: (1995 — 2004)
- **mid-century**: (2045 — 2054)
- **end-of-century**: (2085 — 2094)

For each scenario, the WRF model is run with each of the three GCM outputs,
producing three individual decades of weather data for each scenario.

In other words, 30 years of downscaled climate data is produced for each
decadal scenario.

By using the outputs from three different GCMs, rather than a single model,
Argonne's climate projections better account for the internal uncertainty
associated with any single model.

Each year's worth of data includes weather outputs for every 3 hours, or 8
modeled outputs per day.

While this allows for a high degree of granularity in assessing future climate
models, there are many different ways to analyze this data; however, there are
several important common methodologies share across all variables presented in
this portal.

Most variables are presented as annual or seasonal averages of daily
observations, yet each annual / seasonal average draws upon all three different
climate model runs for that scenario and the ten years of data produced by each
model.


::: {.callout-tip title="Ensemble Mean" collapse="true"}

Each variable (e.g. `total_annual_precipitation`) for a given scenario (e.g.
_Mid-century RCP4.5_) is produced by calculating an individual estimate for
each of the 30 years of climate data associated with that scenario,  and then
taking the average of 30 estimates.

This result is what we term the **ensemble mean**.

:::

## Metadata

The links below direc to the REST service of the gridded data. Metadata,
descriptions, and field names were last updated on 11/7/2022.

1. [Temperature Minimum – Annual](https://disgeoportal.egs.anl.gov/arcgis/rest/services/CCRDS/Precipitation_Annual_Total_Inches/MapServer)
2. [Temperature Minimum – Seasonal](https://disgeoportal.egs.anl.gov/arcgis/rest/services/CCRDS/Precipitation_Annual_Total_Inches/MapServer)
3. [Temperature Maximum – Annual](https://disgeoportal.egs.anl.gov/arcgis/rest/services/CCRDS/Temperature_Maximum_Annual/MapServer)
4. [Temperature Maximum – Seasonal](https://disgeoportal.egs.anl.gov/arcgis/rest/services/CCRDS/Temperature_Maximum_Seasonal/MapServer)
5. [Precipitation – Annual Total](https://disgeoportal.egs.anl.gov/arcgis/rest/services/CCRDS/Precipitation_Annual_Total_Inches/MapServer)
6. [Precipitation None – Annual Average](https://disgeoportal.egs.anl.gov/arcgis/rest/services/CCRDS/Precipitation_ConsecutiveDaysZeroPrecipitation/MapServer)
7. [Wind Speed – Annual Average](https://disgeoportal.egs.anl.gov/arcgis/rest/services/CCRDS/Wind_Speed_MPH/MapServer)
8. [Cooling Degree Days – Annual Total](https://disgeoportal.egs.anl.gov/arcgis/rest/services/CCRDS/Cooling_Degree_Days_Annual/MapServer)
9. [Heating Degree Days – Annual Total](https://disgeoportal.egs.anl.gov/arcgis/rest/services/CCRDS/Heating_Degree_Days_Annual/MapServer)

## Temperature (Annual)

Each climate model generates temperature readings every 3 hours, or 8 temperature readings per day.

The maximum daily temperature refers to the highest of these 8 readings, which
often occurs in the middle of the daytime and is comparable to the 'high
temperature' in a daily weather forecast.

Similarly, the minimum daily temperature refers to the lowest of these 8 readings, which often occurs overnight and is comparable to the 'low temperature' in a daily weather forecast.

Argonne calculated the annual average of both the maximum and minimum daily temperatures. 

These daily high / low readings were then used to calculate the annual average maximum or minimum daily temperature for that scenario's model year (e.g. the average max daily temperature for 2045 using the CCSM model under RCP4.5).

This process was repeated for each year within a given time period / scenario (e.g. 2046, 2047, and so forth) across all three climate models (CCSM, GFDL, and HadGEM).

Finally, the 30 individual annual averatges for a given tim period/scenario were themselves averaged, producing a multi-model ensemble mean that represents the annual average of the maximum or minimum daily temperature for a given time period / scenario.
