author: "Sam Foreman"
date: "2023-06-26"
toc: true
number-sections: true
bibliography: references.bib
# title: "Generative Modeling and Efficient Sampling (for LQCD)"
# affiliation: "Argonne National Laboratory"
theme: darkly
execute:
  freeze: true
project:
  type: website
  preview:
    port: 4200
website:
  title: "Climate Analysis with ClimRR"
  twitter-card: true
  navbar:
    background: "#252525"
    foreground: "#A9A9B3"
    left:
      - href: index.qmd
        text: Analysis
  open-graph: true
  repo-url: https://github.com/saforem2/quarto-examples
  repo-actions: [edit, issue]
  google-analytics: G-XVM2Y822Y1
  sidebar:
    contents: auto
  page-footer: 
    left: "Copyright 2023, Sam Foreman" 
    right: 
      - icon: github
        href: https://github.com/saforem2/quarto-examples
      - icon: twitter
        href: https://twitter.com/saforem2
format:
  html:
    embed-resources: true
    page-layout: full
    fig-responsive: true
    code-fold: show
    anchor-sections: true
    linkcolor: "#00B7E5"
    highlight-style: atom-one
    code-tools:
      source: true
    toc: true
    html-math-method: katex
    theme: [dark, custom.scss]
      # - light: [light, custom.scss]
    css: [css/default.css, css/callouts.css, css/code-callout.css]
  revealjs:
    title-block-style: none
    slide-number: c/t
    title-slide-style: pandoc
    chalkboard:
      buttons: false
    auto-animate: true
    reference-location: section
    touch: true
    # loop: true
    pause: false
    # classoption: fleqn
    # fig-responsive: true
    footnotes-hover: true
    citations-hover: true
    preview-links: true
    controls-tutorial: true
    controls: false
    logo: "https://raw.githubusercontent.com/saforem2/anl-job-talk/main/docs/assets/anl.svg"
    history: false
    # margin: 0.15
    theme: [dark, custom.scss]
      # - light: [light, custom.scss]
    css: [css/default.css, css/callouts.css, css/code-callout.css]
    menu:
      width: "half"
    # menu:
    #   side: right
    #   width: wide
    self-contained: false
    embed-resources: false
    self-contained-math: false
    center: true
    highlight-style: "atom-one"
    default-image-extension: svg
    code-line-numbers: true
    code-overflow: scroll
    html-math-method: katex
    fig-align: center
    execute:
      freeze: auto
    mermaid:
      theme: dark
